GET http://localhost:5000/test
content-type: application/json


### REGISTER
POST http://localhost:5000/user
Content-Type: application/json

{
   "name": "jack122",
   "email": "jack122@test.com",
   "password": "jack08"
}


### LOGIN
POST http://localhost:5000/user/login
Content-Type: application/json

{
   "email": "test@test.com",
   "password": "123456"
}

### Get ALL USERS
GET http://localhost:5000/user?search=j
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2NiMmMyZTczYzU2NDI0YmUzM2Q4NSIsImlhdCI6MTY0MDg2MDM4NiwiZXhwIjoxNjQxNDY1MTg2fQ.WGPqZHpA9JXHo1BmXx1DuKRTrTSsd-VSYKglQ1bLl4Y